import ShopNAvbar from "../components/ShopNAvbar";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <ShopNAvbar />
        {children}
      </body>
    </html>
  );
}
