import { Inter } from "next/font/google";
import "../../globals.css";
import Navbar from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lexardi Lab",
  description: "Generated by create next app",
};

export default function StudioLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
